// ============ Item and inventory system ============
const Items = (() => {
  const DEFS = {
    carbon:      { name: 'Carbon', desc: 'A basic fuel element extracted from plant life. Powers the mining beam and life support systems.', max: 250, color: '#6a6a6a' },
    ferrite:     { name: 'Ferrite Dust', desc: 'A common metallic dust mined from rocky terrain. The basic material for construction and repair.', max: 250, color: '#b0855a' },
    magferrite:  { name: 'Magnetised Ferrite', desc: 'A rare iron mineral magnetized by geological activity. Used to repair advanced technology components.', max: 250, color: '#e0913a' },
    copper:      { name: 'Copper', desc: 'A faintly shimmering stellar metal used to manufacture colorful technology components.', max: 250, color: '#3fc9a0' },
    sodium:      { name: 'Sodium', desc: 'A reactive element abundant in fluorescent yellow plants. Recharges hazard protection.', max: 250, color: '#ffd040' },
    dihydrogen:  { name: 'Di-hydrogen', desc: 'Crystallized hydrogen found throughout the universe. A key ingredient in starship fuel.', max: 250, color: '#4fa8e8' },
    oxygen:      { name: 'Oxygen', desc: 'A vital life support resource. Can be harvested from red oxygen-rich plants.', max: 250, color: '#ff5a4a' },
    cobalt:      { name: 'Cobalt', desc: 'A blue metal crystallized deep within caves, charged with ionic energy.', max: 250, color: '#5a7aff' },
    metalplate:  { name: 'Metal Plating', desc: 'Armor plating forged from ferrite dust. Essential for starship repairs.', max: 10, color: '#9aa5ad', craft: true },
    dihygel:     { name: 'Di-hydrogen Jelly', desc: 'Highly concentrated di-hydrogen fuel gel used by starship launch thrusters.', max: 10, color: '#4fa8e8', craft: true },
    nanotube:    { name: 'Carbon Nanotube', desc: 'A microscopic structure woven from pure carbon. Used for multi-tool and engine repairs.', max: 10, color: '#888888', craft: true },
    terrain:     { name: 'Terrain Block', desc: 'Standard building material generated by the terrain manipulator. Right-click to place.', max: 250, color: '#6a7a82' },
  };

  const RECIPES = [
    { out: 'metalplate', n: 1, req: [['ferrite', 30]] },
    { out: 'dihygel', n: 1, req: [['dihydrogen', 40]] },
    { out: 'nanotube', n: 1, req: [['carbon', 50]] },
    { out: 'terrain', n: 20, req: [['ferrite', 10]] },
  ];

  const SLOTS = 18;
  let inv = []; // { id, n }
  let creative = false;

  function reset() { inv = []; creative = false; }

  function setCreative(on) {
    creative = on;
    if (on) {
      inv = [];
      Object.keys(DEFS).forEach(id => inv.push({ id, n: DEFS[id].max }));
    }
  }

  function count(id) {
    if (creative) return 9999;
    return inv.reduce((s, it) => s + (it && it.id === id ? it.n : 0), 0);
  }

  function add(id, n) {
    if (creative) return n;
    const def = DEFS[id];
    let remaining = n;
    // Fill existing stacks
    for (const it of inv) {
      if (it && it.id === id && it.n < def.max) {
        const take = Math.min(remaining, def.max - it.n);
        it.n += take; remaining -= take;
        if (!remaining) break;
      }
    }
    // New slot
    while (remaining > 0) {
      if (inv.filter(Boolean).length >= SLOTS) return n - remaining; // Full
      const take = Math.min(remaining, def.max);
      let placed = false;
      for (let i = 0; i < SLOTS; i++) {
        if (!inv[i]) { inv[i] = { id, n: take }; placed = true; break; }
      }
      if (!placed) { inv.push({ id, n: take }); }
      remaining -= take;
    }
    return n;
  }

  function remove(id, n) {
    if (creative) return true;
    if (count(id) < n) return false;
    let remaining = n;
    for (let i = inv.length - 1; i >= 0; i--) {
      const it = inv[i];
      if (it && it.id === id) {
        const take = Math.min(remaining, it.n);
        it.n -= take; remaining -= take;
        if (it.n <= 0) inv[i] = null;
        if (!remaining) break;
      }
    }
    return true;
  }

  function canCraft(recipe) {
    return recipe.req.every(([id, n]) => count(id) >= n);
  }

  function craft(recipe) {
    if (!canCraft(recipe)) return false;
    recipe.req.forEach(([id, n]) => remove(id, n));
    add(recipe.out, recipe.n);
    return true;
  }

  return { DEFS, RECIPES, SLOTS, reset, count, add, remove, canCraft, craft, setCreative,
    get creative() { return creative; }, get inv() { return inv; } };
})();
